# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.11.0'
pod 'Firebase/Auth', '~> 5.11.0'
pod 'Firebase/Database', '~> 5.11.0'
pod 'Firebase/Messaging', '~> 5.11.0'

target 'murecycleapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for murecycleapp

  target 'murecycleapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'murecycleappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
